# Global RAG Configuration
chunk_limits:
  min_chars: 800
  max_chars: 2000
  overlap_percent: 15

embedding:
  model: "text-embedding-3-large"
  dimensions: 3072

kg:
  edge_types:
    - develops
    - uses_component
    - inventor_of
    - authored_by
    - affiliated_with
    - competes_with
    - cites
    - improves_upon
    - related_to
    - implements
    - extends

  entity_kinds:
    - technology
    - organization
    - product
    - person
    - component
    - concept
    - method
    - dataset
    - patent
    - paper

quality_gates:
  min_tier1_identifier_coverage: 0.90
  max_out_of_bounds_chunks: 0.05
  min_edges_with_evidence: 0.80
  required_embedding_coverage: 0.95

processing:
  max_retries: 3
  batch_size: 5
  timeout_seconds: 300